# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c90fc2061e630e8b4229c5a9c62e6270c503322aa039ed9f0aab29868020dee0f2c240332e31dea3821a318787972c581ab8aac460cdd98d4e366548ad0889dd

test:
  secret_key_base: 6da9e637e4cb1ce4f8b408f527b7a536d9206d5fa8bed4d43e458383674242059694aa8c2142ce32b5172b730a071fe5d6aac001b89d64e45ae9d637a4abddb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
